### ISSUE TITLE
plugin dir missing

### ISSUE THREAD

**Issue by arioch** [voxpupuli/puppet-collectd#212]
For some plugins (e.g. python ones) I'd have to provide a plugin file.
However the path to store those files isn't defined in the module.

I'd like to add it but I need some additional information where to store those files.
This is what I have so far:

```
Archlinux:
Debian: /var/lib/collectd
FreeBSD:
Gentoo:
Redhat: 
  32bit: /usr/lib/collectd
  63bit: /usr/lib64/collectd
Solaris:
Suse:
default: /var/lib/collectd
```

Anyone know how to fill in the blanks?
