### ISSUE TITLE
Python module configs should be quoted

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-collectd#425]
I ran into this while trying to deploy a module.

```shell
[root@jump1 ~]# cat /etc/collectd.d/python-config.conf 
# Generated by Puppet
<Plugin "python">
  ModulePath "/usr/share/collectd/python"
  LogTraces false
  Interactive false
  Import "puppet_reports"

  <Module "puppet_reports">
    ReportsDir /var/lib/puppet/reports
  </Module>
</Plugin>
[root@jump1 ~]# service collectd stop
Stopping collectd:                                         [  OK  ]
[root@jump1 ~]# service collectd start
Starting collectd: Parse error in file `/etc/collectd.d/python-config.conf', line 136 near `/': syntax error, unexpected SLASH
yyparse returned error #1
configfile: Cannot read file `/etc/collectd.d/python-config.conf'.
Unable to read config file /etc/collectd.conf.
Error: Reading the config file failed!
Read the syslog for details.
not starting due to configuration error
```

YAML used for configuration via hiera:

```yaml
collectd::plugin::python::modules:
  'puppet_reports':
    config:
      ReportsDir: '/var/lib/puppet/reports'
    script_source: 'puppet:///modules/profiles/collectd/python/puppet_reports.py
```
