### ISSUE TITLE
Hiera Support

### ISSUE THREAD

**Issue by iyappan-dcis** [voxpupuli/puppet-collectd#886]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

defining values in Hiera does not work, but works when defined in class. I am using the below format.

collectd::plugin::cpu::reportbystate: true

collectd::plugin::write_graphite::carbon::mygraphite::graphitehost: graphite-1.xxxxx
collectd::plugin::write_graphite::carbon::mygraphite::graphiteport: 2003
collectd::plugin::write_graphite::carbon::mygraphite::graphiteprefix: collectd.
collectd::plugin::write_graphite::carbon::mygraphite::protocol: tcp

**Comment by iyappan-dcis** [comment]
@juniorsysadmin Any support ?

**Comment by NatGuyton** [comment]
for the write_graphite module, I would not expect:

collectd::plugin::write_graphite::carbon::mygraphite::graphitehost: graphite-1.xxxxx

to work, but would expect:

collectd::plugin::write_graphite::carbon::graphitehost: graphite-1.xxxxx

**Comment by steve--d** [comment]
I'm not able to conjure the correct hiera format either.

**Comment by jcasals** [comment]
Hi @iyappan-dcis, 

Sorry I didn't see this, maybe I'm late and you already fixed it, but this is how I have it working.

```
collectd::plugin::write_graphite::carbons:
  graphite:
    graphitehost: 'graphite.domain.com'
    graphiteport: 2013
    graphiteprefix: "instance.cluster."
    separateinstances: false
```

Hope it helps somebody at least.

Cheers,

Jordi
